#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# ///
"""Argus cost model.

Prices are pulled from `scripts/pricing_lookup.out` and `scripts/pricing_lookup_v2.out`,
which were themselves generated by querying the AWS Price List API in us-east-1
on 2026-09-19. See `scripts/pricing_lookup.py` and `pricing_lookup_v2.py`.

Per amazon-bedrock and aws-billing-and-cost-management skills, arithmetic on
cost data lives in a script. Never in prose.

Every rate below has a source line. Update via:
  uv run scripts/pricing_lookup.py
  uv run scripts/pricing_lookup_v2.py
Then re-inspect and edit constants here if any drifted.

Usage:
  python3 scripts/cost_model.py                              # default: 100 clients, 3 events/week
  python3 scripts/cost_model.py --clients 10 --events 1      # demo scenario
  python3 scripts/cost_model.py --clients 500 --events 5     # mid-size firm
  python3 scripts/cost_model.py --no-cache                   # cache disabled
  python3 scripts/cost_model.py --auditor2-pct 0.20          # more high-stakes claims
"""
from __future__ import annotations
import argparse
from dataclasses import dataclass

# ----------------------------------------------------------------------
# Prices per 1,000 tokens, us-east-1, on-demand.
# Source: `scripts/pricing_lookup.out` (2026-09-19 run against AWS Price
# List API service code `AmazonBedrock`).
# ----------------------------------------------------------------------
BEDROCK = {
    "nova-micro": {"in": 0.000035, "out": 0.00014, "cache_read": 0.00000875, "cache_write": 0.000035},
    "nova-lite":  {"in": 0.00006,  "out": 0.00024, "cache_read": 0.000015,   "cache_write": 0.00006},
    "nova-pro":   {"in": 0.0008,   "out": 0.0032,  "cache_read": 0.0002,     "cache_write": 0.0008},
    # Claude 3 Haiku output rate approximated at 5x input (standard Anthropic
    # ratio on Bedrock). Verify via a live invocation and CloudWatch dimension
    # before publishing this in the writeup.
    "claude-3-haiku": {"in": 0.00025, "out": 0.00125, "cache_read": None, "cache_write": None},
}

# Standard AWS rates, us-east-1.
# Source: `scripts/pricing_lookup.out` + `pricing_lookup_v2.out`.
KMS_KEY_MONTHLY = 1.00                    # awskms us-east-1-KMS-Keys
KMS_REQUEST = 0.03 / 10_000               # awskms us-east-1-KMS-Requests (per request)
DYNAMODB_READ_PER_M = 0.125               # AmazonDynamoDB ReadRequestUnits
DYNAMODB_WRITE_PER_M = 0.625              # AmazonDynamoDB WriteRequestUnits
CLOUDWATCH_LOGS_STORAGE_GB_MO = 0.03      # AmazonCloudWatch TimedStorage-ByteHrs
CLOUDWATCH_LOGS_INGEST_PER_GB = 0.50      # Standard rate per AWS docs (not surfaced in Price List API v2 sweep)
S3_STORAGE_STANDARD_GB_MO = 0.023         # AmazonS3, ballpark for hackathon scale
AMPLIFY_REQUESTS_PER_M = 0.30             # AWSAmplify HostingComputeRequestCount
COGNITO_MAU_LITE = 0.0055                 # AmazonCognito Lite tier 1 (Argus fits Lite pool)

# ----------------------------------------------------------------------
# Agent shape assumptions. Update as we validate real prompt sizes.
# ----------------------------------------------------------------------
@dataclass
class AgentSpec:
    name: str
    model: str
    in_tokens: int
    out_tokens: int
    # How many times this agent fires per PolicyDelta pipeline run.
    # Some agents fire once per delta (Sentinel), others fire per client (Analyst).
    calls_shape: str  # "per-delta" or "per-client"
    # Multiplier: what fraction of calls happen? Auditor 2 only fires on high-stakes claims.
    fires_pct: float = 1.0

AGENTS: list[AgentSpec] = [
    AgentSpec("sentinel",  "nova-micro",      in_tokens=5000, out_tokens=500,  calls_shape="per-delta"),
    AgentSpec("analyst",   "nova-pro",        in_tokens=4000, out_tokens=1000, calls_shape="per-client"),
    AgentSpec("auditor1",  "claude-3-haiku",  in_tokens=5000, out_tokens=500,  calls_shape="per-client"),
    AgentSpec("auditor2",  "nova-lite",       in_tokens=5000, out_tokens=500,  calls_shape="per-client", fires_pct=0.10),
    AgentSpec("anchor",    "nova-micro",      in_tokens=2000, out_tokens=500,  calls_shape="per-client"),
    AgentSpec("composer",  "nova-lite",       in_tokens=1000, out_tokens=800,  calls_shape="per-client"),
]

# Recall runs once per day, one full re-scan of the corpus.
RECALL_INPUT = 20_000
RECALL_OUTPUT = 500
RECALL_MODEL = "nova-micro"

# ----------------------------------------------------------------------
# Cost model.
# ----------------------------------------------------------------------
def agent_calls(agent: AgentSpec, clients: int) -> float:
    base = 1 if agent.calls_shape == "per-delta" else clients
    return base * agent.fires_pct

def cost_per_call(agent: AgentSpec, use_cache: bool, cached_fraction: float = 0.80) -> tuple[float, float]:
    """Return (first_call_cost, subsequent_call_cost) in USD.

    First call is treated as full input rate (or cache-write rate). Subsequent
    calls in the same TTL burst read cached_fraction from cache and pay full
    rate on the rest.
    """
    m = BEDROCK[agent.model]
    in_k = agent.in_tokens / 1000
    out_k = agent.out_tokens / 1000
    full_input_cost = in_k * m["in"]
    full_output_cost = out_k * m["out"]

    first = full_input_cost + full_output_cost  # cache_write ~= input rate for Nova (per Price List)
    if not use_cache or m.get("cache_read") is None:
        return (first, first)
    cached_input = in_k * cached_fraction * m["cache_read"]
    uncached_input = in_k * (1 - cached_fraction) * m["in"]
    subsequent = cached_input + uncached_input + full_output_cost
    return (first, subsequent)

def cost_per_policy_event(clients: int, use_cache: bool, cached_fraction: float, auditor2_pct: float) -> dict:
    """Return per-agent breakdown for one PolicyDelta processed against `clients`."""
    per_agent = {}
    for agent in AGENTS:
        # Override Auditor 2's fires_pct if provided
        fires_pct = auditor2_pct if agent.name == "auditor2" else agent.fires_pct
        base_calls = 1 if agent.calls_shape == "per-delta" else clients
        calls = int(round(base_calls * fires_pct))
        first, subsequent = cost_per_call(agent, use_cache, cached_fraction)
        if calls == 0:
            per_agent[agent.name] = 0.0
        elif calls == 1:
            per_agent[agent.name] = first
        else:
            per_agent[agent.name] = first + (calls - 1) * subsequent
    return per_agent

def daily_recall_cost(use_cache: bool) -> float:
    m = BEDROCK[RECALL_MODEL]
    return (RECALL_INPUT / 1000) * m["in"] + (RECALL_OUTPUT / 1000) * m["out"]

def infra_monthly_baseline(rcics: int = 1) -> dict:
    return {
        "kms_signing_key": KMS_KEY_MONTHLY,
        "cognito_mau": max(0.0, (rcics - 10)) * COGNITO_MAU_LITE,  # Lite tier free up to 10 MAU
        # DynamoDB, S3, Lambda, API Gateway HTTP, Step Functions Express, EventBridge
        # are all effectively $0 at idle for our shape.
        "cloudwatch_logs_storage": 0.10,                  # ~3 GB retained
        "cloudwatch_logs_ingest": 0.25,                   # ~0.5 GB/mo during dev
    }

# ----------------------------------------------------------------------
# CLI.
# ----------------------------------------------------------------------
def main() -> None:
    ap = argparse.ArgumentParser(description="Argus monthly cost model")
    ap.add_argument("--clients", type=int, default=100, help="Caseload size per RCIC (default: 100)")
    ap.add_argument("--events", type=int, default=3, help="Policy events per week (default: 3)")
    ap.add_argument("--rcics", type=int, default=1, help="Number of active RCICs (default: 1)")
    ap.add_argument("--no-cache", action="store_true", help="Disable prompt caching")
    ap.add_argument("--cached-fraction", type=float, default=0.80, help="Fraction of input cached on burst (default: 0.80)")
    ap.add_argument("--auditor2-pct", type=float, default=0.10, help="Fraction of claims that trigger Auditor 2 (default: 0.10)")
    args = ap.parse_args()

    use_cache = not args.no_cache
    per_agent = cost_per_policy_event(args.clients, use_cache, args.cached_fraction, args.auditor2_pct)
    per_event = sum(per_agent.values())
    monthly_events = args.events * (52 / 12)  # weekly to monthly
    monthly_bedrock = per_event * monthly_events * args.rcics
    monthly_recall = daily_recall_cost(use_cache) * 30 * args.rcics
    infra = infra_monthly_baseline(args.rcics)
    infra_total = sum(infra.values())
    grand_total = monthly_bedrock + monthly_recall + infra_total

    print(f"\nArgus cost model")
    print(f"  Clients per RCIC: {args.clients}")
    print(f"  Policy events per week: {args.events}")
    print(f"  Active RCICs: {args.rcics}")
    print(f"  Cache: {'ON' if use_cache else 'OFF'} ({args.cached_fraction:.0%} cached on burst)")
    print(f"  Auditor 2 fires on: {args.auditor2_pct:.0%} of claims")
    print()
    print(f"Per-policy-event breakdown (single RCIC, {args.clients} clients):")
    for name, usd in per_agent.items():
        calls_note = "1 call" if AGENTS[[a.name for a in AGENTS].index(name)].calls_shape == "per-delta" else f"{args.clients} calls"
        print(f"  {name:12s}  ${usd:>8.4f}   ({calls_note})")
    print(f"  {'TOTAL':12s}  ${per_event:>8.4f}   per PolicyDelta run")
    print()
    print(f"Monthly rollup:")
    print(f"  Bedrock (all agents):    ${monthly_bedrock:>10.2f}   ({monthly_events:.1f} events x {args.rcics} RCICs)")
    print(f"  Bedrock (Recall daily):  ${monthly_recall:>10.2f}   (30 daily re-scans x {args.rcics} RCICs)")
    for k, v in infra.items():
        print(f"  {k:24s} ${v:>10.2f}")
    print(f"  {'TOTAL':24s} ${grand_total:>10.2f}   per month")
    print()
    if args.rcics > 0:
        print(f"Per-RCIC per month: ${grand_total / args.rcics:.2f}")
        print(f"Per-client per month: ${grand_total / (args.rcics * args.clients):.4f}")
    print()
    print("Incumbent tools charge CA$29 to CA$225 per user per month (see docs/argus-design.md Section 15).")
    print("Argus's compute cost per RCIC beats that floor by a wide margin. Margin room for gross profit.")

if __name__ == "__main__":
    main()
